spring:
  application:
    name: "eurekaserver"


  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness_state:
      enabled: true
    liveness_state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true